### ISSUE TITLE
Problem if try generate docs when $modelClass = false

### ISSUE THREAD

**Issue by njspok** [thiagoarioli/yii2-rest-doc-slade-version#1]
If controller attribute modelClass specify how false (unnecessary set)

```
class SomeRESTController extends Controller {
    public $allowedActions = ['create'];
    public $modelClass = false; // model not specify
```

Im try generate docs

```
Exception 'ReflectionException' with message 'Class  does not exist'

in /var/www/html/vendor/pahanini/yii2-rest-doc/models/ControllerParser.php:64

Stack trace:
#0 /var/www/html/vendor/pahanini/yii2-rest-doc/models/ControllerParser.php(64): ReflectionClass->__construct('')
#1 /var/www/html/vendor/pahanini/yii2-rest-doc/components/Context.php(39): pahanini\restdoc\models\ControllerParser->parse(Object(pahanini\restdoc\models\ControllerDoc))
#2 /var/www/html/vendor/pahanini/yii2-rest-doc/components/Context.php(120): pahanini\restdoc\components\Context->addControllerDoc('\\backend\\module...')
#3 /var/www/html/vendor/pahanini/yii2-rest-doc/components/Context.php(99): pahanini\restdoc\components\Context->addFile('/var/www/html/b...')
#4 /var/www/html/vendor/pahanini/yii2-rest-doc/components/Context.php(58): pahanini\restdoc\components\Context->addDirs(Array)
#5 /var/www/html/vendor/pahanini/yii2-rest-doc/components/Context.php(82): pahanini\restdoc\components\Context->addModule(Object(backend\modules\api\modules\v3\Module))
#6 /var/www/html/vendor/pahanini/yii2-rest-doc/controllers/BuildController.php(54): pahanini\restdoc\components\Context->addModules(Array)
#7 [internal function]: pahanini\restdoc\controllers\BuildController->actionRun()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('backendapidoc', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('backendapidoc', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /var/www/html/yii(31): yii\base\Application->run()
#16 {main}
make: *** [apigen] Error 1
```

Maybe in controller php-doc specify fields?

**Comment by thiagoarioli** [comment]
can you make your question in english?
Thanks
